### ISSUE TITLE
Angular 13 build issue with 3.2.0

### ISSUE THREAD

**Issue by dereekb** [vdolek/angular-resize-event#76]
My CI ran into a build issue with the 3.2.0 release while running Angular 13.

```

./node_modules/angular-resize-event/fesm2015/angular-resize-event.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/home/circleci/setup-test/myproject/node_modules/angular-resize-event/fesm2015/angular-resize-event.mjs: This application depends upon a library published using Angular version 14.0.2, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  31 | }
  32 | ResizedDirective.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.0.2", ngImport: i0, type: ResizedDirective, deps: [{ token: i0.ElementRef }, { token: i0.NgZone }], target: i0.ɵɵFactoryTarget.Directive });
> 33 | ResizedDirective.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "14.0.2", type: ResizedDirective, selector: "[resized]", outputs: { resized: "resized" }, ngImport: i0 });
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  34 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.0.2", ngImport: i0, type: ResizedDirective, decorators: [{
  35 |             type: Directive,
  36 |             args: [{'
    at run (/home/circleci/setup-test/myproject/node_modules/@babel/core/lib/transformation/index.js:39:15)
    at run.next (<anonymous>)
    at Function.transform (/home/circleci/setup-test/myproject/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/circleci/setup-test/myproject/node_modules/gensync/index.js:261:32)
    at /home/circleci/setup-test/myproject/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/circleci/setup-test/myproject/node_modules/gensync/index.js:223:11)
    at /home/circleci/setup-test/myproject/node_modules/gensync/index.js:189:28
    at /home/circleci/setup-test/myproject/node_modules/@babel/core/lib/gensync-utils/async.js:84:7
    at /home/circleci/setup-test/myproject/node_modules/gensync/index.js:113:33
    at step (/home/circleci/setup-test/myproject/node_modules/gensync/index.js:287:14)
    at /home/circleci/setup-test/myproject/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/circleci/setup-test/myproject/node_modules/gensync/index.js:223:11)
```

https://app.circleci.com/pipelines/github/dereekb/dbx-components/1485/workflows/e1bd96fc-97de-494e-93c8-53492750ffd9/jobs/4088/parallel-runs/0/steps/0-110

Don't know if that's intentional or not, since the package.json states only Angular 14, but the release page says `support for Angular 12-14`.

I'll be locking the dependency/version to `"angular-resize-event": "~3.1.1"` for now.

**Comment by vdolek** [comment]
I have tried it for Angular 13 and it works for me. Example: https://stackblitz.com/edit/angular-resize-event-playground-angular-13

**Comment by dereekb** [comment]
Ok, and I see the [actual package.json](https://github.com/vdolek/angular-resize-event/blob/master/projects/angular-resize-event/package.json) has the 12-<15 range for the version too.

Weird, probably something on my end for that test.

**Comment by oadrian2** [comment]
I can confirm the same issue. It seems to be complaining about the ng-packager version being 14.0.2 (i.e. built for Angular 14).

**Comment by wolfpackt99** [comment]
We had same issue and had to roll back to `~3.1.1`

**Comment by dertuerke** [comment]
same issue her with angular 13.x

**Comment by softengi** [comment]
any update we have on this? Thanks.

**Comment by mloffer** [comment]
I also had to lock to 3.1.1 to get it to work with Angular 13.
